Update webrtc to branch-heads/64.
Header files aren't in a subdirectory anymore, so "find talk/ webrtc/"
becomes just "find .".
https://webrtc.googlesource.com/src/+/bb547203bfebcc478b263c4e9ca173c6fd5a0c5d

We set use_custom_libcxx=false and use_custom_libcxx_for_host=false.
This version of WebRTC seems to prefer to link with a bundled copy of
libc++ (libcxx) by default. This library has an ABI incompatible with
the libstdc++ that we use when linking with go-webrtc. You will get
undefined references because of different std::string types.

We set use_lld=false for mac. The default use_lld=true causes the use of
an option -fuse-ld=lld, which is not supported by our version of Clang:
clang-3.8: error: invalid linker name in argument '-fuse-ld=lld'

We define WEBRTC_LINUX/WEBRTC_MAC as appropriate. For mac, WEBRTC_MAC is
needed in include/rtc_base/byteorder.h; without it, the build fails with
a failure to open <endian.h> (taking the WEBRTC_POSIX case).
WEBRTC_LINUX doesn't seem to be required (I got a successful build
without it), but define it for symmetry.

webrtc-linux.patch and webrtc-mac.patch needed rebasing. mac also needed
two new patches: one to remove another no-cross-compiling assumption,
and one to remove an option that our older LLVM doesn't support.

linux's former gtk2 dependency is now gtk3.

I had to manually delete "gmock" and "gtest" directories:
	Error: Command 'git checkout --quiet 60c665fffe7dc505fdd5d30f9dbcbc50dde1e017' returned non-zero exit status 1 in tor-browser-build/gclient/webrtc/src/testing
	error: The following untracked working tree files would be overwritten by checkout:
		gmock/include/gmock/gmock-actions.h
		gmock/include/gmock/gmock-generated-function-mockers.h
		gmock/include/gmock/gmock-matchers.h
		gmock/include/gmock/gmock.h
		gtest/include/gtest/gtest-death-test.h
		gtest/include/gtest/gtest-message.h
		gtest/include/gtest/gtest-param-test.h
		gtest/include/gtest/gtest-spi.h
		gtest/include/gtest/gtest.h
		gtest/include/gtest/gtest_prod.h
	Please move or remove them before you switch branches.